### ISSUE TITLE
如何对单个视频进行预测

### ISSUE THREAD

**Issue by Cursky** [MengyuanChen21/CVPR2022-FTCL#1]
### 如果我打算使用训练好的模型对单个视频进行预测该如何做？

谢谢！
祝 生活愉快

**Comment by MengyuanChen21** [comment]
First of all, thank you for your interest in our work. If the single video you are talking about is an untrimmed raw video without any pre-processing, you need to convert it into 2048-dimensional features with a pre-trained I3D model. For the pre-trained feature extraction, we refer you to the official [TensorFlow-based I3D repo](https://github.com/deepmind/kinetics-i3d) and the third-party [PyTorch-based I3D repo](https://github.com/piergiaj/pytorch-i3d). There are detailed operations guides for the feature extraction. If the single video talked about is just one of the testing videos of the THUMOS14 dataset, simply modifying the dataset section of the code will work.
