### ISSUE TITLE
关于ACM-Net训练部分怎么达到42.6%

### ISSUE THREAD

**Issue by dongfengxijian** [MengyuanChen21/CVPR2022-FTCL#2]
感谢你分享的工作。我为改任何参数的情况下运行`python main_thu.py --group baseline --model_name acmnet --epochs 500`只得到了37.7%的精度，求指导如何能达到42.6%？
### ### ### ### ### ### ### ### ### ### ### ### 
![image](https://user-images.githubusercontent.com/24863806/167105168-7d4d5bb4-3340-44e0-95df-bce9270be758.png)
### ### ### ### ### ### ### ### ### ### ### ###

**Comment by MengyuanChen21** [comment]
First of all, thank you for your attention to our work! As we mentioned in the Training section of the README, according to our experiments, the training of ACM-Net is not very stable under different random seeds.  We tried twenty random seeds from zero to nineteen, and only five of them achieved 42.6@mAP Avg. Therefore, I suggest trying several different random number seeds to achieve a higher accuracy. Please let me know if you have any further questions.
